[tool.poetry]
name = "pyepsilla"
version = "0.3.9"
description = ""
authors = ["Epsilla <info@epsilla.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10"
boto3 = "^1.35.5"
posthog = "^3.6.0"
py-machineid = "^0.6.0"
sentry-sdk = "^2.13.0"
requests = "^2.32.3"
pydantic = "^2.8.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
